bet/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.OpenBets.as_view(), name='bet'),
]

codestar/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("bet/", include("bet.urls"), name="bet"),
    path("about/", include("about.urls"), name="about"),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include("blog.urls"), name='blog-urls'), 
    path("accounts/", include("allauth.urls")),     
]

bet/models.py
from django.db import models
import uuid 
from django.contrib.auth.models import User

RESULT = ((0, "Draw"), (1, "Home"), (2, "Away"))
STATUS = ((0, "Pending"), (1, "Win"), (-1, "Lose"))

# Create your models here.
class Bet(models.Model):
    
    id = models.UUIDField(
        primary_key = True, 
        default = uuid.uuid4, 
        editable = False)
    stake = models.DecimalField(max_digits=10, decimal_places=2)
    updated_on = models.DateTimeField(auto_now=True)
    settled = models.IntegerField(choices=STATUS, default=0)
    punter = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="placed_by")
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    payout =  models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.punter} | {self.id}"



class Line(models.Model):
    home_team = models.CharField(max_length=16)
    away_team = models.CharField(max_length=16)
    prediction = models.IntegerField(choices=RESULT, default=1)
    odds = models.DecimalField(max_digits=10, decimal_places=3)
    match_result = models.IntegerField(choices=STATUS, default=0)
    status = models.IntegerField(choices=STATUS, default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    bets = models.ManyToManyField(Bet)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.home_team} v {self.away_team}"

bet/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Bet, Line

# Create your views here.
class OpenBets(generic.ListView):
    """
    Renders the bets page
    """           
    queryset = Bet.objects.filter(settled='0')
    template_name = "bet/bets.html"
    paginate_by = 5

bet/templates/bet/bets.html
{% extends "base.html" %}

{% block content %}

<!-- index.html content starts here -->
<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for bet in bet_list %}
                <div class="col-md-12">
                    <div class="card mb-12">
                        <div class="card-body">
                            <div class="image-container">
                                <div class="image-flash">
                                    <p class="author">Punter: {{ bet.punter }}</p>
                                </div>
                            </div>
                                <h2 class="card-title">{{ bet.stake }}</h2>
                                <p class="card-text">{{ bet.settled }}</p>
                            </a>

                            <hr />
                            <p class="card-text text-muted h6">{{ bet.created_on}}
                            </p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link"> PREV &laquo;</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

<!-- index.html content ends here -->
{% endblock %}

{% block copyright %}

Copyright 2024 Barry Mays

{% endblock %}